[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
name = "realize"
version = "0.1.0"

[dependencies]
error-chain = "0.8.1"
linked-hash-map = "0.3.0"
sha1 = "0.2.0"
slog-journald = "1.0.0"
slog-term = "1.3.5"

[dependencies.slog]
features = ["release_max_level_trace", "max_level_trace"]
version = "1.4.1"
